accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.Login.as_view(),name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('index/',views.index,name='index'),
    

]

mydevelop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import include,url

#プロジェクト(mydevelop)とそれぞれのアプリケーション1(polls,admin,accounts)
#を繋げるためのurls.py
urlpatterns = [
    path('polls/',include('polls.urls')),
    path('accounts/',include('accounts.urls')),
    path('ocero/',include('ocero.urls')),
    #path('',include('user_sessions.urls','user_sessions')),
    path('admin/', admin.site.urls),
]

ocero/urls.py
from django.urls import path
from . import views

app_name = 'ocero'

urlpatterns = [
    path('',views.index,name = 'index'),#通常
    path('change/',views.change,name = 'change'),#通常
    path('onceindex/',views.onceindex,name = 'onceindex'),
]

polls/urls.py
from django.urls import path,include

from . import views

#app_nameをつけることで、Djangoのプロジェクト間のURLを区別できる
#
app_name = 'polls'

#polls.urlsモジュールと結びつけることが出来る。
#第一引数はpath接続するため
urlpatterns = [
    #path('',views.index,name = 'index'),#通常
    path('',views.IndexView.as_view(),name='index'),#generic viewの書き方
    #path('<int:question_id>/',views.detail,name = 'detail'),
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),#generic viewの書き方
    #path('<int:question_id>/result/',views.results,name = 'results'),
    path('<int:pk>/results',views.ResultsView.as_view(),name='results'),#generic viewの書き方
    path('<int:question_id>/vote/',views.vote,name = 'vote'),

]

polls/models.py
import datetime#python標準モジュール

from django.db import models
from django.utils import timezone#Djangoのタイムゾーン関連ユーティリティ

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date  published')

    #Question.objects.all()
    #一覧出そうとしたときに下の文がないと
    #<QuerySet [<Question: Question object (1)>]>
    #あると<QuerySet [<Question: What's up?>]>
    #おそらく中の文字(今回でいうとquestion_textを返す)
    def __str__(self):
        return self.question_text
    
    #一番最近のものを認識するため
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    


# Create your models here.

polls/views.py
#djangoのショートカット
#return render(requestオブジェクト,テンプレート名('polls/index.html),(任意)辞書(context))
from django.shortcuts import render
#djangoの404エラー構文
from django.shortcuts import get_object_or_404


"""スタブメソッドなくなったため必要なし??
#スタブメソッドを使用するなら残す
#スタブ:下位モジュールの変わり、空の代用品用
from django.http import HttpResponse
"""
#ひとつの引数(リダイレクト先のURL)をとる。
#POSTデータが成功した後は常にHTTPResponseRedirectを返す必要がある。
##from django.contrib.sessions.backends.base import SessionBase
from django.http import HttpResponseRedirect,request#,HttpRequest
"""djangoのショートカットget_object_or_404がHttp404を楽にしてくれたため必要なし
#404エラー送出(httpのモジュール)
from django.http import Http404
"""


#ビュー関数中でURLのハードコードを妨げる事ができる。
#制御を渡したいビュー名とそのビューに与えるURLパターンの位置引数を与える。
from django.urls import reverse


#汎用ビューをしようするため
from django.views import generic


"""djangoのrenderを使用すれば必要なし?
#templateを読み込む
from django.template import loader
"""


from django.utils import timezone


#modelsパッケージ
from .models import Question,Choice


#urlsのpath()を通すことで以下の関数が使用できる。


#各汎用ビューは自分がどのモデルに対して動作するのか知っておく必要がある。
#(model属性を使用して提供される)

#ListViewは「オブジェクトのリストを表示する」

class IndexView(generic.ListView):
    
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        #日付を比較してチェック
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

        """
        #上から5つ
        return Question.objects.order_by('-pub_date')[:5]
        """
    def get_context_data(self, **kwargs):
        # セッションを追加する
        
        #self.request.session['username'] = self.request.user.username
        
        return super(IndexView, self).get_context_data(**kwargs)

#DetailViewは「あるタイプのオブジェクト詳細ページを表示する」
#DetailView汎用ビューには"pk"という名前でURLからプライマリキー(DBの登録番号のようなもの)
#キャプチャして渡すことになっているので、汎用ビュー向けにquestion_idをpkに変更している。
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        #未来の質問に到達させないために制約
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'



def vote(request,question_id):
    #question_idが存在しなければ、エラー表示(djangoのショートカット)(detailと一緒)
    question = get_object_or_404(Question,pk=question_id)

    try:
        #request.POSTはキーを指定すると送信したデータにアクセスできる。
        #今回は選択された選択肢のIDを文字列として返す。
        #POSTデータに(voteという投票(form)でPOSTデータが送信されたにもかかわらず)choiceが何も選択されなければexcept文
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request,'polls/detail.html',{
            'question':question,
            'error_message':"You didn't selected a choice.",
            #'aiueo':"aiueo",.html側で受け取らなくても送れる(受け取った方がよいが)
        })
    else:
        selected_choice.votes +=1
        selected_choice.save()

    return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))



#
##汎用ビューIndexViewの元関数
#def index(request):
#    #最新質問5つをlistにいれる
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    
#    '''responseじゃなくtemplate.renderをしようし、requestをできるように
#    #', 'でlatest_question_listの中身を繋げる
#    output = ', '.join([q.question_text for q in latest_question_list])
#    return HttpResponse(output)
#    '''
#
#    """djangoのrender使うため必要なくなった?
#    #templateにディレクトリtemplateのpolls/indexをいれる
#    template = loader.get_template('polls/index.html')
#    """
#
#    #contextに'latest_question_list'としてlatest_question_listをいれる(マッピング)
#    context = {'latest_question_list':latest_question_list,}
#    
#    """djangoのrender使うため必要なくなった?
#    #テンプレートの レンダリング (rendering) では、コンテキストから値を取り 
#    # 出して変数という「穴」に埋め、全てのブロックタグを実行します。
#    #templateのrenderメソッドをつかってrequest情報を全てでcontextを指定し送る
#    #template(indexに).render(記述する)(comtext(リスト),request(通信機能))
#    return HttpResponse(template.render(context,request))
#    """
#
#    #dhangoのrender関数(第一引数:request,第二:テンプレ名,第三:辞書)
#    return render(request,'polls/index.html',context
#
#
##汎用ビューDetailViewの元関数
#def detail(request,question_id):
#    #以下のtryを自動でしてくれる(djangoのショートカット)
#    question = get_object_or_404(Question,pk=question_id)
#
#    """djangoの404エラー構文を使うためtryとかは必要なくなった?
#    try:
#        #question_idをgetしてみる
#        question = Question.objects.get(pk=question_id)
#
#    #そのquestion_idが存在しなければ
#    except Question.DoesNotExist:
#        #エラー文を出力
#        raise Http404("Question does not exist")
#   
#    #except通らなければ、
#    """
#    #renderでquestionの中身をdetai.htmlに送る
#    return render(request,'polls/detail.html',{'question':question})
#    
#
#    """renderで値を送れるようになったため必要なくなった?
#    #空の代用品
#    return HttpResponse("you're question %s" % question_id)
#    
#
#
##汎用ビューResultsViewの元関数
#def results(request,question_id):
#    #question_idが存在しなければ、エラー表示(djangoのショートカット)(detailと一緒)
#    question = get_object_or_404(Question,pk=question_id)
#
#    return render(request,'polls/results.html',{'question':question})

templates/polls/detail.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>
    {% extends "accounts/base.html" %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    {% block content %}
    
    <main role="main" class="container">
        <div>
            <!--テンプレートシステムは、変数の属性にアクセスするためにドット検索の構文を使用-->
            <h1 class="mt-5">{{ question.question_text }}</h1>
        </div>
        {% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
    </main>
    <!--ブロック分け-->
    <div class="container" >
        <!--pollsプロジェクトのvote関数に"POST"通信行う-->
        <!--サーバ側のデータの更新を行う際はPOST通信--> 
        <!--actionでどのプロジェクトのどの関数と何をやり取りするか-->
        <!--polls:voteでurls.pyで指定したvoteの名前使用-->
        <form action="{%url 'polls:vote' question.id %}" method ="POST">
            <!--XSS対策(テンプレートタグ)-->
            {% csrf_token %}
            <div class="row mb-3"><!--bootstrap-->
                {% for choice in question.choice_set.all %}
                <!--radioボタンとその中身-->
                <div class="form-check container themed-container">
                    <!--radioボタン-->
                    <div class="row mb-3">
                        <div class = "col-2 themed-grid-col">
                            <div class="row">
                                <div class="col-md-6 themed-grid-col"></div>
                                <div class="col-md-6 themed-grid-col">
                                    <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter}}" value ="{{choice.id}}" checked>
                                </div>
                            </div>
                        </div>
                        <div class = "col-4 themed-grid-col">
                            <div class="row">
                                <div class="col-md-6 themed-grid-col">
                                    <label class="form-check-label" for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <input type="submit" class="btn btn-primary" value="Vote">
        </form>
        <a class="btn btn-primary" href="{% url 'polls:index' %}">目次に戻る??</a>
    </div>
    <!--
    <li><a class="btn btn-primary" href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    -->
    </div> 
    <div>
        <img src="../../static/polls/images/days_res.png" class="rounded float-left">
    </div> 
    
    {% endblock %}
</body>

templates/polls/index.html
<head>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   
   
</head>
<body>
    {% extends "accounts/base.html" %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

    {% block content %}
    {% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}. Thanks for logging in.</p>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <!--
        """下はハードコードされたコード("/polls/"の所)->pollsの後に必ず入る->階層変わった際の変化できない
        <li><a class="btn btn-primary" href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
        -->
        
        <!--polls:detailでpollsという名前空間(pollsのurl.pyでapp_nameで指定)のdetailを指定-->
        <li><a class="btn btn-primary" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    {%else%}
        <a class="btn btn-primary" href="{% url 'accounts:login' %}">ログイン</a>
    {% endif %}
    <div>
        <img src="../../static/polls/images/days_res.png" class="rounded float-left">
    </div>
    <p>セッション表示テスト</p>
    username：{{ request.session.username }}<br>
    <a class="btn btn-primary" href="{% url 'accounts:index' %}">メニュー??</a>

    {% endblock %}    

</body>

templates/polls/results.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>
    {% extends "accounts/base.html" %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    {% block content %}
    <main role="main" class="container">
        <div class="starter-template">
            <!--テンプレートシステムは、変数の属性にアクセスするためにドット検索の構文を使用-->
            <h1 class="mt-5">{{ question.question_text }}</h1>
        </div>
    </main>
    <!--ブロック分け-->
    <div class="container" >
        <div class="row mb-3"><!--bootstrap-->
            {% for choice in question.choice_set.all %}
            <!--radioボタンとその中身-->
            <div class="container themed-container">
                <div class="row mb-3">
                    <div class="col-4 themed-grid-col">{{ choice.choice_text }}</div>
                    <div class="col-4 themed-grid-col">------</div>
                    <div class="col-4 themed-grid-col">{{choice.votes}} vote{{choice.votes|pluralize}}</div>
                </div>
            </div>
            {% endfor %}
        </div>
        <a class="btn btn-primary" href="{% url 'polls:detail' question.id %}">Vote again??</a>
        <a class="btn btn-primary" href="{% url 'polls:index' %}">目次に戻る??</a>
    </div>
    <!--
    <li><a class="btn btn-primary" href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    -->
    <p>セッション表示テスト</p>
    username：{{ request.session.username }}<br>
    <div>
        <img src="../../static/polls/images/days_res.png" class="rounded float-left">
    </div> 
    {% endblock %}
</body>