accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.Login.as_view(),name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('index/',views.index,name='index'),
    

]

mydevelop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import include,url

#プロジェクト(mydevelop)とそれぞれのアプリケーション1(polls,admin,accounts)
#を繋げるためのurls.py
urlpatterns = [
    path('polls/',include('polls.urls')),
    path('accounts/',include('accounts.urls')),
    path('ocero/',include('ocero.urls')),
    #path('',include('user_sessions.urls','user_sessions')),
    path('admin/', admin.site.urls),
]

ocero/urls.py
from django.urls import path
from . import views

app_name = 'ocero'

urlpatterns = [
    path('',views.index,name = 'index'),#通常
    path('change/',views.change,name = 'change'),#通常
    path('onceindex/',views.onceindex,name = 'onceindex'),
]

polls/urls.py
from django.urls import path,include

from . import views

#app_nameをつけることで、Djangoのプロジェクト間のURLを区別できる
#
app_name = 'polls'

#polls.urlsモジュールと結びつけることが出来る。
#第一引数はpath接続するため
urlpatterns = [
    #path('',views.index,name = 'index'),#通常
    path('',views.IndexView.as_view(),name='index'),#generic viewの書き方
    #path('<int:question_id>/',views.detail,name = 'detail'),
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),#generic viewの書き方
    #path('<int:question_id>/result/',views.results,name = 'results'),
    path('<int:pk>/results',views.ResultsView.as_view(),name='results'),#generic viewの書き方
    path('<int:question_id>/vote/',views.vote,name = 'vote'),

]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
# AuthenticationFormからこのコードは派生し、
# 明示的にユーザー名とパスワードのフィールドをオーバーライドして、
# プレースホルダーテキストを追加している。

#プレースホルダーテキストとは
#  入力フォームの内側に表示される借り入れのテキストのこと
#  ユーザが入力欄にカーソルを合わせると文字が消える仕様のものが多い
from django.contrib.auth.forms import(
    #このクラスを利用すると簡単にログオン用フォームを生成できる
    AuthenticationForm
)

#ログオン用のフォームクラスを定義
class LoginForm(AuthenticationForm):
    #ログオンフォームの定義
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for fields in self.fields.values():
            #全てのフォームの部品のクラス属性に[form-comtrol]を指定(bootstrapのフォームを利用するため)
            fields.widget.attrs['class'] = 'form-control'
            #全てのフォームの部品に[placeholder]を定義して、入力フォームにフォーム名が表示されるように指定
            fields.widget.attrs['placeholder'] = fields.label

        
#全フォームはAuthenticationFormクラス内で定義されているfields
#ウィジェット(widget)はHTMLの入力エレメントを表現するためにオブジェクト
#field.widget.attrs[属性] = <設定値>という形でフォームのデザインを定義できる

accounts/views.py
from django.shortcuts import render

#このクラスを継承するだけで、継承したクラスに遷移する場合はログインが必要になる。
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.sessions.backends.base import SessionBase
from django.http import HttpRequest
"""
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
"""
#ログイン後に元にいたページにリダイレクト処理

#ログインURLがGETメソッドで呼ばれた場合にはログイン用のフォームをテンプレートで
# 利用できるようにした状態でログインページのテンプレートを返す 
# ログインURLがPOSTメソッドで呼ばれた場合にはユーザーのログイン処理を実行
# ログイン「に成功すれば、nextというパラメータに指定されたパスのURLにリダイレクトする
# nextが指定されていない場合はsetting.pyファイルのsettings.LOGIM_REDIRECT_URLに指定してURLにリダイレクトする 
from django.contrib.auth.views import(
    LoginView,LogoutView,
)


from . forms import LoginForm

class Login(LoginView):
    #ログインページ
    form_class = LoginForm
    template_name = 'accounts/login.html'
    #next = みたいな感じでどこにリダイレクトするか指定できる
    #書かないのならば、プロジェクト直下のLOGIN_REDIRECT_URLに指定すべき
    

#ログインしているユーザでないとログアウトボタンを押せないようにするため
#(ログインしているユーザだけが制御できるようにするため)
# -> ログインしていないのにログアウトボタン押されるとバグになる
class Logout(LoginRequiredMixin,LogoutView):
    #ログインページ
    #template_nameでログアウト後に表示されるテンプレートファイルを指定
    template_name = 'accounts/login.html'


def index(request):
    #ログイン後に遷移するテスト用のTOPページを定義した関数
    #request.session['user_id'] = user_id
    request.session['username'] = request.user.username
    return render(request,'accounts/index.html')

templates/accounts/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>Tutorialサイト</title>
</head>
<body>
    <!-- ナビバー -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'accounts:login' %}">Tutorialサイト</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!--ログイン中の人にしか見えない-->
        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'accounts:logout' %}">ログアウト</a>
        {% endif %}
      </div>

      
    </nav>

    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

templates/accounts/index.html
{% extends "accounts/base.html" %}
{% block content %}
{% if user.is_authenticated %}
ログオンしました。
<p>セッション表示テスト</p>
    username：{{ request.session.username }}<br>
<a class="btn btn-primary" href="{% url 'polls:index' %}">投票サイト??</a>
<a class="btn btn-primary" href="{% url 'ocero:index' %}">オセロ??</a>
{%else%}
        <a class="btn btn-primary" href="{% url 'accounts:login' %}">ログイン</a>
{% endif %}
{% endblock %}

templates/accounts/login.html
{% extends "accounts/base.html" %}
{% block content %}
<form action="" method="POST">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                    <!--テンプレートタグのfor文でformオブジェクトから要素をひとつずつfield変数に格納-->
                    <!--{{field}}でフォームを表示-->
                    {% for field in form %}
                    {{ field }}
                     <hr>
        　　        {% endfor %}
                    <!--form.non_field_errorsで認証時エラーを取得できる-->
          　　　　  {% for error in form.non_field_errors %}
                  <div class="alert alert-danger" role="alert">
                      <!--赤枠でerrorが表示される-->
                       <p>{{ error }}</p>
                  </div>
　　　　　　　       {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
            </div>
        </div>
    </div>
</form>
{% endblock %}