accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.Login.as_view(),name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('index/',views.index,name='index'),
    

]

mydevelop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import include,url

#プロジェクト(mydevelop)とそれぞれのアプリケーション1(polls,admin,accounts)
#を繋げるためのurls.py
urlpatterns = [
    path('polls/',include('polls.urls')),
    path('accounts/',include('accounts.urls')),
    path('ocero/',include('ocero.urls')),
    #path('',include('user_sessions.urls','user_sessions')),
    path('admin/', admin.site.urls),
]

ocero/urls.py
from django.urls import path
from . import views

app_name = 'ocero'

urlpatterns = [
    path('',views.index,name = 'index'),#通常
    path('change/',views.change,name = 'change'),#通常
    path('onceindex/',views.onceindex,name = 'onceindex'),
]

ocero/models.py
from django.db import models

# Create your models here.

ocero/views.py
from django.shortcuts import render

from django.http import request,HttpResponseRedirect
from django.urls import reverse


class colt():
    def __init__(self,x,y):
        self.state = 0
        self.x = x
        self.y = y

    def flip(self):
        self.state = self.state*(-1)

    def put(self,turn):
        self.state = turn

field =[[0 for j in range(8)] for i in range(8)]
turncount = 0
judge = 0

def init():
    for k in range(0,8):
        for l in range(0,8):
            field[l][k] = colt(l,k)
            if k==3 and l==3 or k==4 and l==4:
                field[l][k].put(1)
            if k==3 and l==4 or k==4 and l==3:
                field[l][k].put(-1)

init()

# Create your views here.


def index(request):
    global turncount
    global judge
    turncount+=1
    explore()
    black = countBW(1)
    white = countBW(-1)
    putbool = putjudge()
    if black+white==64 or black==0 or white==0:
        judge = 2
    context = {'field':field,'black':black,'white':white,'putbool':putbool,'judge':judge}
    return render(request,'ocero/index.html',context)

def putjudge():
    for i in range(0,8):
        for j in range(0,8):
            if field[j][i].state==2:
                return False
    global judge
    judge+=1
    return True

def onceindex(request):
    return HttpResponseRedirect(reverse('ocero:index'))


def change(request):
    global turncount
    if request.method =='POST':
        for i in range(0,8):
            for j in range(0,8):
                if str(j)+ ' '+ str(i) in request.POST:
                    if field[j][i].state == 2:
                        global judge
                        judge=0
                        putColt(j,i)
                        flick(j,i,True)
                    else:
                        turncount+=1
    
    return HttpResponseRedirect(reverse('ocero:index'))

def putColt(x,y):
    turn = count()
    field[x][y].put(turn)

def deleteColt(x,y):
    field[x][y].put(0)

def countBW(bwcolt):
    coltcount = 0
    for i in range(0,8):
        for j in range(0,8):
            if field[j][i].state==bwcolt:
                coltcount += 1
    return coltcount

def count():
    #total = countBW(1) + countBW(-1)
    if turncount%2==0:
        turn = 1
    else:
        turn = -1
    return turn

def explore():
    for i in range(0,8):
        for j in range(0,8):
            if field[j][i].state == 0 or field[j][i].state == 2:
                putColt(j,i)
                flick(j,i,False)
                if field[j][i].state != 2:
                    deleteColt(j,i)

def flick(x,y,mode):
    for i in range(-1,2):
        for j in range(-1,2):
            if i != 0 or j != 0:
                changeColt(x,y,j,i,mode)


def changeColt(x,y,xarrow,yarrow,mode):
    if x+xarrow>=0 and x+xarrow<=7 and y+yarrow>=0 and y+yarrow<=7:
        next = field[x+xarrow][y+yarrow].state
        if next*(-1) == field[x][y].state:
            for i in range(2,8):
                if xarrow<0 and x-i<0:
                    break
                elif xarrow>0 and x+i>7:
                    break
                if yarrow<0 and y-i<0:
                    break
                elif yarrow>0 and y+i>7:
                    break
                if field[x+i*xarrow][y+i*yarrow].state == 0:
                    break
                if field[x+i*xarrow][y+i*yarrow].state == field[x][y].state:
                    if mode == True:
                        for j in range(1,i):
                            field[x+j*xarrow][y+j*yarrow].state = field[x][y].state
                    else:
                        field[x][y].state = 2

templates/ocero/index.html
<head>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   
   
</head>
<body>
    {% extends "accounts/base.html" %}
    {% block content %}
    <div class="container" >
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <p>オセロゲーム</p>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
    <form action="{%url 'ocero:change'%}" method ="POST">
        {% csrf_token %}
    <div class="container" >
        <div class="row">
            {% for fild in field %}
            <div class="col-md-2 col-md-offset-1"></div>
            {% for fd in fild %}
                <div class="col-md-1">
                    
                    {%if fd.state == 1%}
                        <input type="submit" class="btn btn-primary" name="{{fd.x}} {{fd.y}}" value="●">
                    {%elif fd.state == -1%}
                        <input type="submit" class="btn btn-primary" name="{{fd.x}} {{fd.y}}" value="〇">
                    {%elif fd.state == 2%}
                        <input type="submit" class="btn btn-primary text-success" name="{{fd.x}} {{fd.y}}" value="★">
                    {%else%}
                        <input type="submit" class="btn text-danger" name="{{fd.x}} {{fd.y}}" value="×">
                    {%endif%}
                </div>    
            {% endfor %}  
            <div class="col-md-2 col-md-offset-1"></div>
            {% endfor %} 
        </div> 
    </div>
    </form>

    <div class="container" >
        <div class="row">
            <p>Black : {{black}} , White : {{white}}</p>
        </div>
        <div class="row">
            {%if judge >= 2%}
                {% if black > white %}
                <p>Black の勝ち</p>
                {% elif black == white %}
                <p>引き分け</p>
                {% else %}
                <p>White の勝ち</p>
                {% endif %}
            {%else%}
                {% if putbool %}
                    <form action="{%url 'ocero:onceindex'%}" method ="POST">
                        {% csrf_token %}
                        <div class="container" >
                            <input type="submit" class="btn btn-primary" name="1" value="●">
                        </div>
                    </form>
                {%endif%}
            {% endif %}
        </div>
    </div>

    
    <a class="btn btn-primary" href="{% url 'accounts:index' %}">メニュー??</a>
    {% endblock %}   
</body>